codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "20...100"

  status:
    project:
      default:
        target: 25%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 25%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

  ignore:
    - "tests/*"
    - "examples/*"
    - "docs/*"
    - "setup.py"
    - "*/test_*.py"
    - "*/__init__.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true
